<a href="https://colab.research.google.com/github/Uzoemeka/DEM0-REPO/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np

In [6]:
2-2

0

In [7]:
my_list  = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [8]:
np1 = np.random.rand(3,4)
np1


array([[0.52742839, 0.10778257, 0.64276162, 0.68795256],
       [0.93339171, 0.55452791, 0.03353434, 0.05521409],
       [0.8815033 , 0.41152191, 0.42735889, 0.31373907]])

In [9]:
np1.dtype

dtype('float64')

In [10]:
np2 = np.random.rand(3)
np2

array([0.2530782 , 0.18177303, 0.16961897])

In [11]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0582, -0.4899, -1.1445,  1.7375],
        [-0.5871, -0.0852, -1.5123, -0.8150],
        [-0.8246, -0.1658, -1.1257, -2.4994]])

In [12]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [13]:
# creat tensor out numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.5274, 0.1078, 0.6428, 0.6880],
        [0.9334, 0.5545, 0.0335, 0.0552],
        [0.8815, 0.4115, 0.4274, 0.3137]], dtype=torch.float64)

In [14]:
import torch

In [16]:
my_torch = torch.randn(10)
my_torch

tensor([ 0.7712, -0.9288,  1.4214,  0.7408,  0.7512, -0.6513, -0.6000, -1.7877,
        -0.2334, -0.8814])

In [20]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[ 0.7712, -0.9288,  1.4214,  0.7408,  0.7512],
        [-0.6513, -0.6000, -1.7877, -0.2334, -0.8814]])

In [21]:
#reshape if we dont know the number of items using -1
my_torch2 = torch.randn(15)
my_torch2

tensor([-0.2095,  1.7338,  0.8823, -0.7787, -1.0576, -0.2589, -0.3180,  1.3241,
        -0.9949,  0.6931,  0.6004,  0.1508, -0.2934,  0.0022, -0.9458])

In [26]:
my_torch2 = my_torch2.reshape(-1, 5)
my_torch2

tensor([[-0.2095,  1.7338,  0.8823, -0.7787, -1.0576],
        [-0.2589, -0.3180,  1.3241, -0.9949,  0.6931],
        [ 0.6004,  0.1508, -0.2934,  0.0022, -0.9458]])

In [27]:
my_torch3 = my_torch2.view(3,5)
my_torch3

tensor([[-0.2095,  1.7338,  0.8823, -0.7787, -1.0576],
        [-0.2589, -0.3180,  1.3241, -0.9949,  0.6931],
        [ 0.6004,  0.1508, -0.2934,  0.0022, -0.9458]])

In [28]:
# difference between reshape and view

In [29]:
my_torch5 = torch.randn(10)
my_torch5

tensor([ 1.5052, -0.4113, -0.3012,  1.1067, -0.1912,  0.1752, -0.9940,  0.5235,
         0.0156,  2.0802])

In [31]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[ 1.5052, -0.4113, -0.3012,  1.1067, -0.1912],
        [ 0.1752, -0.9940,  0.5235,  0.0156,  2.0802]])

In [32]:
my_torch5[1] = 4141
my_torch5

tensor([ 1.5052e+00,  4.1410e+03, -3.0121e-01,  1.1067e+00, -1.9123e-01,
         1.7525e-01, -9.9399e-01,  5.2353e-01,  1.5610e-02,  2.0802e+00])

In [33]:
my_torch6

tensor([[ 1.5052e+00,  4.1410e+03, -3.0121e-01,  1.1067e+00, -1.9123e-01],
        [ 1.7525e-01, -9.9399e-01,  5.2353e-01,  1.5610e-02,  2.0802e+00]])

In [34]:
# slices
my_torch5[7]

tensor(0.5235)

In [35]:
# grab a slice
my_torch6[:,0]

tensor([1.5052, 0.1752])

In [39]:
my_torch6[:,4:]

tensor([[-0.1912],
        [ 2.0802]])

In [55]:
# maths operations
tens_a = torch.tensor([1,2,3,4])
tens_b = torch.tensor([5,6,7,8])

In [56]:
tens_a + tens_b

tensor([ 6,  8, 10, 12])

In [57]:
tens_a - tens_b

tensor([-4, -4, -4, -4])

In [58]:
torch.add(tens_a, tens_b)

tensor([ 6,  8, 10, 12])

In [59]:
tens_a*tens_b

tensor([ 5, 12, 21, 32])

In [60]:
tens_a/tens_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [61]:
tens_a % tens_b

tensor([1, 2, 3, 4])

In [62]:
tens_b % tens_a

tensor([0, 0, 1, 0])

In [63]:
torch.pow(tens_a, tens_b)

tensor([    1,    64,  2187, 65536])

In [64]:
tens_a.add(tens_b)

tensor([ 6,  8, 10, 12])

In [66]:
# reassignment
tens_b.add_(tens_a)
tens_b

tensor([ 7, 10, 13, 16])

In [ ]:
# Neural network